# Generated by Django 5.2.17 on 2026-08-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_token', models.CharField(max_length=256)),
                ('owner_user_id', models.CharField(blank=True, max_length=128)),
                ('printer_name', models.CharField(blank=True, max_length=256)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=512)),
                ('user_id', models.CharField(blank=True, max_length=128)),
                ('pages_spec', models.CharField(default='all', max_length=128)),
                ('color_mode', models.CharField(choices=[('bw', 'BlackWhite'), ('color', 'Color')], default='bw', max_length=16)),
                ('price_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('printed', 'Printed'), ('failed', 'Failed')], default='pending_payment', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('provider_payment_id', models.CharField(blank=True, max_length=256)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('printing', 'Printing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='printjobs.device')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='printjobs.order')),
            ],
        ),
    ]
